name: OpenNMT
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - git+https://github.com/pytorch/text
  - chardet==3.0.4
  - future==0.17.1
  - idna==2.8
  - numpy==1.16.1
  - opencv-python==4.0.0.21
  - requests==2.21.0
  - six==1.12.0
  - torch==0.4.1
  - tqdm==4.31.1
  - urllib3==1.24.1

